#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

# add empty directories that are needed by Hugo
mkdir -p content data layouts resources/_gen/assets resources/_gen/images
