#!/bin/sh

# script/ship: Generate the website and push it to GitHub Pages.

set -e

hugo -t nix

cd public
git add .
msg="Update site to $(date) version"
if [ -n "$*" ]; then
	msg="$*"
fi
git commit -m "$msg"
git push origin main
