#!/bin/sh

# script/ship: Generate the website and push it to GitHub Pages.

set -e

hugo -t nix

cd public
git add .
msg="rebuilding site $(date)"
if [ -n "$*" ]; then
	msg="$*"
fi
git commit -S -m "$msg"
git push origin master
